version: "3.9"

networks:
  lab_compose:

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./logs:/var/log
      - .:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST=192.168.1.160
      - POSTGRES_NAME=electrochemistry_lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vrag
    networks:
      - lab_compose
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready - U smm -d new_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - lab_compose
    environment:
      - POSTGRES_HOST=192.168.1.160
      - POSTGRES_NAME=electrochemistry_lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vrag
    env_file:
      - .env
    depends_on:
      - db
      - migration
    restart: unless-stopped

  migration:
    image: postgres
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "s.m.mih@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "vrag"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/log/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - lab_compose
  nginx_int:
    image: nginx
    networks:
      - lab_compose

